[package]
name = "xamarin_bundle_tools"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.5", features = ["derive"] }
elf = "0.7.2"
flate2 = "1.0.27"
